version: '3.0'

services:

  geoserver:
    container_name: geoserver
    environment:
      GEOSERVER_DATA_DIR: /var/lib/geoserver_data
    image: chbrandt/geoserver:latest
    ports:
      - ${PORT_GEOSERVER:-8080}:8080
    volumes:
      - geoserver_data:/var/lib/geoserver_data
      - ${VOLUME_PUB:-.}:/mnt/data

  www_data:
    container_name: data
    image: gmap/apaxy:latest
    ports:
      - ${PORT_DATA:-80}:80
    volumes:
      - ${VOLUME_PUB:-.}:/var/www/html/pub

  www_maps:
    container_name: maps
    image: chbrandt/maps-viewer:gmap
    ports:
      - ${PORT_MAPS:-3000}:3000

volumes:
  geoserver_data:
