version: '3.0'

services:

  flask:
    container_name: home
    environment:
      FLASK_ENV: production
    image: chbrandt/data_site:latest
    ports:
      - 80:5000

  geoserver:
    container_name: geoserver
    environment:
      GEOSERVER_DATA_DIR: /var/lib/geoserver_data
    image: chbrandt/geoserver:latest
    ports:
      - ${PORT_GEOSERVER:-8080}:8080
    volumes:
      # - geoserver_data:/var/lib/geoserver_data
      - ${VOLUME_PUB:-./data}:/mnt/data

  jupyterhub:
    container_name: jupyter
    image: chbrandt/gispy:jupyterhub
    ports:
      - ${PORT_JUPYTER:-8888}:8000
    volumes:
      - ${VOLUME_PUB:-./data}:/mnt/data
      - ${VOLUME_JNB:-./notebooks}:/mnt/notebooks

  www_data:
    container_name: data
    image: gmap/apaxy:latest
    ports:
      - ${PORT_DATA:-8282}:80
    volumes:
      - ${VOLUME_PUB:-./data}:/var/www/html/pub

  www_maps:
    container_name: maps
    image: chbrandt/maps-viewer:gmap
    ports:
      - ${PORT_MAPS:-8484}:3000

volumes:
  geoserver_data:
